<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Akron.Telemetry.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Source/Core/akron-telemetry.cs" Link="akron-telemetry.cs" />
    <Compile Include="../../Source/Core/akron-telemetry-worker.cs" Link="akron-telemetry-worker.cs" />
    <PackageReference Include="Sentry" Version="6.12.0" IncludeAssets="compile;runtime" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
