using System.Globalization;
using Celeste;
using Microsoft.Xna.Framework;
using Monocle;

namespace Celeste.Mod.Akron;

public static partial class AkronCommands {
    [Command("akron_status", "show Akron runtime status")]
    public static void Status() {
        Level level = Engine.Scene as Level;
        Player player = level?.Tracker.GetEntity<Player>();
        AkronModuleSession session = AkronModule.Session;
        Log("scene: " + (Engine.Scene?.GetType().Name ?? "null"));
        Log("overlay: " + (AkronModule.IsOverlayVisible ? "visible" : "hidden"));
        Log("overlays: " + SafeStatusValue(() => AkronModule.Settings.DescribePresentationOverlays(), "unavailable"));
        Log("attempt: " + (session == null ? "unavailable" : AkronModuleSettings.FormatStatus(session.AttemptStatus)));
        Log("reason: " + (session == null ? "session unavailable outside active save context" : session.AttemptReason));
        Log("slot: " + AkronModule.Settings.ActiveSavestateSlot);
        Log("freeze: " + (session?.FreezeGameplay.ToString().ToLowerInvariant() ?? "false"));
        Log("timescale: " + (session?.TimescaleMultiplier.ToString("0.0x", CultureInfo.InvariantCulture) ?? "1.0x"));
        LogStartPosStatus(level);
        Log("capture: " + (session == null || string.IsNullOrWhiteSpace(session.LastScreenshotPath) ? "none" : AkronModule.Settings.FormatPathForDisplay(session.LastScreenshotPath)));
        Log("room-capture: " + AkronScreenshotScanner.Describe());
        Log("map-capture: " + AkronScreenshotScanner.Describe());
        Log("capture-export: " + AkronModule.Settings.FormatPathForDisplay(AkronModule.Settings.ScreenshotScannerExportPath));
        Log("capture-format: " + AkronModuleSettings.NormalizeScreenshotScannerImageFormat(AkronModule.Settings.ScreenshotScannerImageFormat));
        Log("capture-markers: " + AkronModule.Settings.ScreenshotScannerExportMarkers.ToString().ToLowerInvariant());
        Log("capture-markers-startpos: " + AkronModule.Settings.ScreenshotScannerExportStartPositions.ToString().ToLowerInvariant());
        Log("capture-markers-autokill: " + AkronModule.Settings.ScreenshotScannerExportAutoKillAreas.ToString().ToLowerInvariant());
        Log("capture-markers-autodeafen: " + AkronModule.Settings.ScreenshotScannerExportAutoDeafenAreas.ToString().ToLowerInvariant());
        Log("capture-freeze-time: " + AkronModule.Settings.ScreenshotScannerFreezeTime.ToString().ToLowerInvariant());
        Log("capture-noclip-hide-madeline: " + AkronModule.Settings.ScreenshotScannerNoclipHideMadeline.ToString().ToLowerInvariant());
        Log("autosave: " + AkronModule.Settings.Autosave.ToString().ToLowerInvariant());
        Log("autosave-interval: " + AkronModule.Settings.AutosaveIntervalSeconds.ToString(CultureInfo.InvariantCulture));
        Log("autosave-hide-saving-icon: " + AkronModule.Settings.AutosaveHideSavingIcon.ToString().ToLowerInvariant());
        Log("deload-spinners-delay: " + AkronModule.Settings.DeloadSpinnerDelaySeconds.ToString("0.###", CultureInfo.InvariantCulture));
        Log("dash-count-stats: " + AkronModule.Settings.DashCountStats.ToString().ToLowerInvariant());
        Log("dash-count-stats-mode: " + AkronModule.Settings.DashCountStatsMode);
        Log("jump-stats: " + AkronModule.Settings.JumpCount.ToString().ToLowerInvariant());
        Log("jump-stats-mode: " + AkronModule.Settings.JumpCountMode);
        Log("sound-volume-count: " + AkronEarAid.Sounds.Length.ToString(CultureInfo.InvariantCulture));
        Log("audio-splitter: " + AkronModule.Settings.AudioSplitter.ToString().ToLowerInvariant());
        Log("audio-splitter-status: " + AkronAudioSplitter.Status());
        Log("proof-mode: " + AkronModule.Settings.ProofModeOverlay.ToString().ToLowerInvariant());
        Log("streamer-mode: " + AkronModule.Settings.StreamerMode.ToString().ToLowerInvariant());
        Log("submission-mode: " + AkronModule.Settings.SubmissionMode.ToString().ToLowerInvariant());
        Log("proof-recorder-guard: " + AkronModule.Settings.ProofRecorderGuard.ToString().ToLowerInvariant());
        Log("end-screen-helper: " + AkronModule.Settings.EndScreenHelper.ToString().ToLowerInvariant());
        Log("pause-tracker: " + AkronModule.Settings.PauseTracker.ToString().ToLowerInvariant());
        Log("pause-tracker-count: " + (session?.PauseTrackerPauseCount.ToString(CultureInfo.InvariantCulture) ?? "0"));
        Log("pause-tracker-rapid-count: " + (session?.PauseTrackerRapidPauseCount.ToString(CultureInfo.InvariantCulture) ?? "0"));
        Log("pause-tracker-paused-seconds: " + (session?.PauseTrackerPausedSeconds.ToString("0.000", CultureInfo.InvariantCulture) ?? "0.000"));
        Log("map-version-stamp: " + AkronModule.Settings.MapVersionStamp.ToString().ToLowerInvariant());
        Log("golden-transparency: " + AkronModule.Settings.GoldenTransparency.ToString().ToLowerInvariant());
        Log("golden-transparency-opacity: " + AkronModule.Settings.GoldenTransparencyOpacity.ToString(CultureInfo.InvariantCulture));
        Log("lag-pauser: " + AkronModule.Settings.LagPauser.ToString().ToLowerInvariant());
        Log("lag-pauser-threshold-ms: " + AkronModule.Settings.LagPauserThresholdMs.ToString(CultureInfo.InvariantCulture));
        Log("lag-pauser-trigger-count: " + (session?.LagPauserTriggerCount.ToString(CultureInfo.InvariantCulture) ?? "0"));
        Log("lag-pauser-last-spike-ms: " + (session?.LagPauserLastSpikeMs.ToString("0.000", CultureInfo.InvariantCulture) ?? "0.000"));
        Log("golden-start-helper-used: " + (session?.UsedGoldenStartHelper.ToString().ToLowerInvariant() ?? "false"));
        Log("journal-snapshot-compare-used: " + (session?.UsedJournalSnapshotCompare.ToString().ToLowerInvariant() ?? "false"));
        Log("journal-snapshot-path: " + (string.IsNullOrWhiteSpace(session?.LastJournalSnapshotPath) ? "none" : AkronModule.Settings.FormatPathForDisplay(session.LastJournalSnapshotPath)));
        Log("journal-compare-summary: " + (string.IsNullOrWhiteSpace(session?.LastJournalCompareSummary) ? "none" : session.LastJournalCompareSummary));
        Log("low-distraction: " + AkronModule.Settings.IsLowDistractionActive().ToString().ToLowerInvariant());
        Log("safe-mode: " + AkronModule.Settings.SafeMode.ToString().ToLowerInvariant());
        Log("consume-menu-input: " + AkronModule.Settings.ConsumeGameplayInputInMenu.ToString().ToLowerInvariant());
        Log("pause-gameplay-in-menu: " + AkronModule.Settings.PauseGameplayInMenu.ToString().ToLowerInvariant());
        Log("overlay-opacity: " + AkronModule.Settings.OverlayOpacity.ToString(CultureInfo.InvariantCulture));
        Log("overlay-theme: " + AkronOverlayThemes.CurrentDisplayName());
        Log("allow-pause-buffering: " + AkronModule.Settings.AllowPauseBuffering.ToString().ToLowerInvariant());
        Log("allow-low-volume: " + AkronModule.Settings.AllowLowVolume.ToString().ToLowerInvariant());
        Log("low-volume-music: " + AkronModule.Settings.LowVolumeMusic.ToString("0.0", CultureInfo.InvariantCulture));
        Log("low-volume-sfx: " + AkronModule.Settings.LowVolumeSfx.ToString("0.0", CultureInfo.InvariantCulture));
        Log("audio-speed: " + AkronRuntimeOptions.DescribeAudioSpeed());
        Log("pitch-shift: " + AkronRuntimeOptions.DescribePitchShift());
        Log("fps-bypass: " + AkronRuntimeOptions.DescribeFpsBypass());
        Log("tps-bypass: " + AkronRuntimeOptions.DescribeTpsBypass());
        Log("frame-bypass-method: " + AkronModule.Settings.FrameBypassMethod);
        Log("frame-bypass-camera: " + AkronModule.Settings.FrameBypassCameraSmoothing);
        Log("frame-bypass-objects: " + AkronModule.Settings.FrameBypassObjectSmoothing);
        Log("frame-bypass-tas-mode: " + AkronModule.Settings.FrameBypassTasMode.ToString().ToLowerInvariant());
        Log("frame-bypass-subpixel-madeline: " + AkronModule.Settings.FrameBypassSubpixelMadeline.ToString().ToLowerInvariant());
        Log("frame-bypass-smooth-background: " + AkronModule.Settings.FrameBypassSmoothBackground.ToString().ToLowerInvariant());
        Log("frame-bypass-smooth-foreground: " + AkronModule.Settings.FrameBypassSmoothForeground.ToString().ToLowerInvariant());
        Log("frame-bypass-hide-edge-gaps: " + AkronModule.Settings.FrameBypassHideStretchedEdges.ToString().ToLowerInvariant());
        Log("frame-bypass-nasty-mode: " + AkronModule.Settings.FrameBypassSillyMode.ToString().ToLowerInvariant());
        Log("free-camera: " + AkronRuntimeOptions.DescribeFreeCamera());
        Log("free-camera-freeze-gameplay: " + AkronModule.Settings.FreeCameraFreezeGameplay.ToString().ToLowerInvariant());
        Log("hide-hud: " + AkronRuntimeOptions.DescribeHudVisibility());
        Log("safe-mode-stats: " + AkronRuntimeOptions.DescribeSafeModeStats());
        if (Settings.Instance != null) {
            Log("current-music-volume: " + Settings.Instance.MusicVolume.ToString(CultureInfo.InvariantCulture));
            Log("current-sfx-volume: " + Settings.Instance.SFXVolume.ToString(CultureInfo.InvariantCulture));
        }
        Log("runtime-music-volume: " + (Audio.MusicVolume * 10f).ToString("0.0", CultureInfo.InvariantCulture));
        Log("runtime-sfx-volume: " + (Audio.SfxVolume * 10f).ToString("0.0", CultureInfo.InvariantCulture));
        Log("unlock-system: " + AkronActions.DescribeUnlockState());
        Log("confirm-retry: " + AkronModule.Settings.ConfirmRetry.ToString().ToLowerInvariant());
        Log("confirm-restart: " + (AkronModule.Settings.ConfirmRestart || AkronModule.Settings.ConfirmRetry).ToString().ToLowerInvariant());
        Log("confirm-reload-room: " + AkronModule.Settings.ConfirmReloadRoom.ToString().ToLowerInvariant());
        Log("confirm-reload-chapter: " + AkronModule.Settings.ConfirmReloadChapter.ToString().ToLowerInvariant());
        Log("confirm-full-reset: " + (AkronModule.Settings.ConfirmFullReset || AkronModule.Settings.ConfirmReloadChapter).ToString().ToLowerInvariant());
        Log("confirm-load-state: " + AkronModule.Settings.ConfirmLoadState.ToString().ToLowerInvariant());
        Log("save-time-and-deaths: " + AkronModule.Settings.SaveTimeAndDeaths.ToString().ToLowerInvariant());
        Log("broker-warnings: " + AkronModule.Settings.SpeedrunToolBrokerWarnings.ToString().ToLowerInvariant());
        Log("indicator-visibility: " + AkronModule.Settings.IndicatorVisibility);
        Log("indicator-corner: " + AkronModule.Settings.IndicatorCorner);
        Log("indicator-offset: " + AkronModule.Settings.IndicatorOffsetX.ToString(CultureInfo.InvariantCulture) + ", " + AkronModule.Settings.IndicatorOffsetY.ToString(CultureInfo.InvariantCulture));
        Log("mouse-visible: " + Engine.Instance.IsMouseVisible.ToString().ToLowerInvariant());
        Log("click-teleport: " + AkronModule.Settings.ClickTeleport.ToString().ToLowerInvariant());
        Log("click-teleport-cursor: " + AkronModuleSettings.DescribeBinding(AkronModule.Settings.ClickTeleportCursor));
        Log("click-teleport-cursor-held: " + (AkronModule.Settings.ClickTeleportCursor?.Check ?? false).ToString().ToLowerInvariant());
        Log("cursor-zoom: " + AkronModule.DescribeCursorZoom(Engine.Scene as Level));
        Log("cursor-zoom-hold: " + AkronModuleSettings.DescribeBinding(AkronModule.Settings.CursorZoomHold));
        Log("room-labels: " + AkronModule.Settings.RoomLabels.ToString().ToLowerInvariant());
        Log("labels-visible: " + AkronModule.Settings.LabelSystemVisible.ToString().ToLowerInvariant());
        Log("room-label-color: " + FormatRgb(AkronModule.Settings.RoomLabelColor));
        Log("input-viewer: " + AkronModule.Settings.InputViewer.ToString().ToLowerInvariant());
        Log("input-history: " + AkronModule.Settings.InputHistoryPanel.ToString().ToLowerInvariant());
        Log("input-history-length: " + AkronModule.Settings.InputHistoryLength.ToString(CultureInfo.InvariantCulture));
        Log("input-history-placement: " + AkronModule.Settings.InputHistoryPlacement);
        Log("input-history-opacity: " + AkronModule.Settings.InputHistoryOpacity.ToString(CultureInfo.InvariantCulture));
        Log("input-history-color: " + FormatRgb(AkronModule.Settings.InputHistoryTextColor));
        Log("input-history-compact: " + AkronModule.Settings.InputHistoryCompact.ToString().ToLowerInvariant());
        Log("input-history-pin-on-death: " + AkronModule.Settings.InputHistoryPinOnDeath.ToString().ToLowerInvariant());
        Log("input-history-show-on-death: " + AkronModule.Settings.InputHistoryShowOnDeath.ToString().ToLowerInvariant());
        Log("input-history-transitions: " + AkronModule.Settings.InputHistoryShowTransitions.ToString().ToLowerInvariant());
        Log("input-history-samples: " + AkronInputHistory.Describe());
        LogControlDisplaySettings();
        LogInputsPerSecondSettings();
        Log("stamina-bar: " + AkronModule.Settings.StaminaBar.ToString().ToLowerInvariant());
        Log("stamina-player-bar: " + AkronModule.Settings.StaminaBarPlayer.ToString().ToLowerInvariant());
        Log("stamina-hud-bar: " + AkronModule.Settings.StaminaBarHud.ToString().ToLowerInvariant());
        Log("stamina-player-position: " + AkronModule.Settings.StaminaBarPlayerPosition);
        Log("stamina-hud-position: " + AkronModule.Settings.StaminaBarHudPosition);
        Log("stamina-style: " + AkronModule.Settings.StaminaBarStyle);
        Log("stamina-player-offset: " + AkronModule.Settings.StaminaPlayerOffsetX.ToString(CultureInfo.InvariantCulture) + ", " + AkronModule.Settings.StaminaPlayerOffsetY.ToString(CultureInfo.InvariantCulture));
        Log("stamina-player-scale: " + AkronModule.Settings.StaminaPlayerScale.ToString(CultureInfo.InvariantCulture));
        Log("stamina-always-visible: " + AkronModule.Settings.StaminaAlwaysVisible.ToString().ToLowerInvariant());
        Log("stamina-danger-marker: " + AkronModule.Settings.StaminaShowDangerMarker.ToString().ToLowerInvariant());
        Log("stamina-change-pulse: " + AkronModule.Settings.StaminaShowChangePulse.ToString().ToLowerInvariant());
        Log("stamina-hud-offset: " + AkronModule.Settings.StaminaHudOffsetX.ToString(CultureInfo.InvariantCulture) + ", " + AkronModule.Settings.StaminaHudOffsetY.ToString(CultureInfo.InvariantCulture));
        Log("dash-bar: " + AkronModule.Settings.DashBar.ToString().ToLowerInvariant());
        Log("dash-player-bar: " + AkronModule.Settings.DashBarPlayer.ToString().ToLowerInvariant());
        Log("dash-hud-bar: " + AkronModule.Settings.DashBarHud.ToString().ToLowerInvariant());
        Log("dash-player-position: " + AkronModule.Settings.DashBarPlayerPosition);
        Log("dash-hud-position: " + AkronModule.Settings.DashBarHudPosition);
        Log("dash-style: " + AkronModule.Settings.DashBarStyle);
        Log("dash-player-offset: " + AkronModule.Settings.DashBarPlayerOffsetX.ToString(CultureInfo.InvariantCulture) + ", " + AkronModule.Settings.DashBarPlayerOffsetY.ToString(CultureInfo.InvariantCulture));
        Log("dash-player-scale: " + AkronModule.Settings.DashBarPlayerScale.ToString(CultureInfo.InvariantCulture));
        Log("dash-always-visible: " + AkronModule.Settings.DashBarAlwaysVisible.ToString().ToLowerInvariant());
        Log("dash-show-label: " + AkronModule.Settings.DashBarShowText.ToString().ToLowerInvariant());
        Log("dash-empty-pips: " + AkronModule.Settings.DashBarShowEmptyPips.ToString().ToLowerInvariant());
        Log("dash-hide-paused: " + AkronModule.Settings.DashBarHideWhilePaused.ToString().ToLowerInvariant());
        Log("dash-hud-offset: " + AkronModule.Settings.DashBarHudOffsetX.ToString(CultureInfo.InvariantCulture) + ", " + AkronModule.Settings.DashBarHudOffsetY.ToString(CultureInfo.InvariantCulture));
        Log("dash-available-color: " + FormatRgb(AkronModule.Settings.DashBarAvailableColor));
        Log("dash-empty-color: " + FormatRgb(AkronModule.Settings.DashBarEmptyColor));
        Log("dash-low-color: " + FormatRgb(AkronModule.Settings.DashBarLowColor));
        Log("dash-fill-color: " + FormatRgb(AkronModule.Settings.DashBarFillColor));
        Log("dash-line-color: " + FormatRgb(AkronModule.Settings.DashBarLineColor));
        LogDashCountSettings();
        LogSpeedNumberSettings();
        LogGroundRefillSettings();
        Log("no-freeze-frames: " + AkronModule.Settings.NoFreezeFrames.ToString().ToLowerInvariant());
        Log("low-stamina-threshold: " + AkronModule.Settings.LowStaminaThreshold.ToString(CultureInfo.InvariantCulture));
        Log("stamina-overflow-color: " + FormatRgb(AkronModule.Settings.StaminaOverflowColor));
        Log("room-timer: " + AkronModule.Settings.RoomTimerWidget.ToString().ToLowerInvariant());
        Log("room-timer-color: " + FormatRgb(AkronModule.Settings.RoomTimerColor));
        Log("death-stats: " + AkronModule.Settings.DeathStatsWidget.ToString().ToLowerInvariant());
        Log("death-stats-color: " + FormatRgb(AkronModule.Settings.DeathStatsColor));
        Log("total-attempts: " + AkronModule.Settings.TotalAttemptsWidget.ToString().ToLowerInvariant());
        Log("total-attempts-color: " + FormatRgb(AkronModule.Settings.TotalAttemptsColor));
        Log("status-labels: " + AkronModule.Settings.StatusLabelsWidget.ToString().ToLowerInvariant());
        Log("status-labels-color: " + FormatRgb(AkronModule.Settings.StatusLabelsColor));
        Log("no-short-numbers: " + AkronModule.Settings.NoShortNumbers.ToString().ToLowerInvariant());
        Log("custom-hud-labels: " + AkronModule.Settings.CustomHudLabels.ToString().ToLowerInvariant());
        Log("custom-hud-label-count: " + (AkronModule.Settings.CustomHudLabelDefinitions?.Count ?? 0).ToString(CultureInfo.InvariantCulture));
        Log("custom-hud-label-active: " + AkronCustomHudLabels.DescribeActive());
        Log("custom-hud-label-padding: " + AkronModule.Settings.CustomHudLabelPadding.ToString(CultureInfo.InvariantCulture));
        Log("custom-hud-label-gap: " + AkronModule.Settings.CustomHudLabelGap.ToString(CultureInfo.InvariantCulture));
        Log("custom-hud-label-variables: " + AkronCustomHudLabels.VariableCatalog());
        Log("hud-cheat-indicator: " + AkronModule.Settings.HudCheatIndicator.ToString().ToLowerInvariant());
        Log("hud-cheat-indicator-anchor: " + AkronModule.Settings.HudCheatIndicatorAnchor);
        Log("hud-cheat-indicator-style: " + AkronModule.Settings.HudCheatIndicatorStyle);
        Log("hud-cheat-indicator-only-flagged: " + AkronModule.Settings.HudCheatIndicatorOnlyFlagged.ToString().ToLowerInvariant());
        if (level != null) {
            int sessionDeaths = level.Session.Deaths;
            int roomDeaths = level.Session.DeathsInCurrentLevel;
            Log("death-stats-session: " + sessionDeaths.ToString(CultureInfo.InvariantCulture));
            Log("death-stats-room: " + roomDeaths.ToString(CultureInfo.InvariantCulture));
            Log("death-stats-total: " + AkronHudRenderer.GetCurrentMapDeathTotal(level).ToString(CultureInfo.InvariantCulture));
        }
        Log("reduced-visual-noise: " + AkronModule.Settings.ReducedVisualNoise.ToString().ToLowerInvariant());
        Log("no-particles: " + AkronModule.Settings.NoParticles.ToString().ToLowerInvariant());
        Log("no-trails: " + AkronModule.Settings.NoTrails.ToString().ToLowerInvariant());
        Log("no-glitch: " + AkronModule.Settings.NoGlitch.ToString().ToLowerInvariant());
        Log("no-anxiety: " + AkronModule.Settings.NoAnxiety.ToString().ToLowerInvariant());
        Log("no-distortion: " + AkronModule.Settings.NoDistortion.ToString().ToLowerInvariant());
        Log("hide-snow: " + AkronModule.Settings.HideSnow.ToString().ToLowerInvariant());
        Log("hide-wind-snow: " + AkronModule.Settings.HideWindSnow.ToString().ToLowerInvariant());
        Log("hide-waterfalls: " + AkronModule.Settings.HideWaterfalls.ToString().ToLowerInvariant());
        Log("hide-tentacles: " + AkronModule.Settings.HideTentacles.ToString().ToLowerInvariant());
        Log("hide-heat-distortion: " + AkronModule.Settings.HideHeatDistortion.ToString().ToLowerInvariant());
        Log("light-level: " + AkronModule.Settings.LightLevel.ToString().ToLowerInvariant());
        Log("light-level-percent: " + AkronModule.Settings.LightLevelPercent.ToString(CultureInfo.InvariantCulture));
        Log("bloom-level: " + AkronModule.Settings.BloomLevel.ToString().ToLowerInvariant());
        Log("bloom-level-percent: " + AkronModule.Settings.BloomLevelPercent.ToString(CultureInfo.InvariantCulture));
        Log("screen-tint: " + AkronModule.Settings.ScreenTint.ToString().ToLowerInvariant());
        Log("screen-tint-color: " + FormatRgb(AkronModule.Settings.ScreenTintColor));
        Log("screen-tint-opacity: " + AkronModule.Settings.ScreenTintOpacity.ToString(CultureInfo.InvariantCulture));
        Log("hide-player: " + AkronModule.Settings.HidePlayer.ToString().ToLowerInvariant());
        Log("no-death-effect: " + AkronModule.Settings.NoDeathEffect.ToString().ToLowerInvariant());
        Log("no-death-wipe: " + AkronModule.Settings.NoDeathWipe.ToString().ToLowerInvariant());
        Log("no-death-wipe-mode: " + AkronModule.Settings.NoDeathWipeMode);
        Log("no-death-wipe-run-callbacks: " + AkronModule.Settings.NoDeathWipeRunCallbacks.ToString().ToLowerInvariant());
        Log("hitboxes: " + AkronModule.Settings.HitboxViewer.ToString().ToLowerInvariant());
        Log("fix-hitbox-pixels: " + AkronModule.Settings.FixHitboxPixels.ToString().ToLowerInvariant());
        Log("hitbox-active-only: " + AkronModule.Settings.HitboxActiveOnly.ToString().ToLowerInvariant());
        Log("hitbox-hide-player: " + AkronModule.Settings.HitboxHidePlayer.ToString().ToLowerInvariant());
        Log("hitbox-hazards: " + AkronModule.Settings.HitboxShowHazards.ToString().ToLowerInvariant());
        Log("hitbox-solids: " + AkronModule.Settings.HitboxShowSolids.ToString().ToLowerInvariant());
        Log("hitbox-triggers: " + AkronModule.Settings.HitboxShowTriggers.ToString().ToLowerInvariant());
        Log("hitbox-last-death: " + AkronModule.Settings.HitboxShowLastDeath.ToString().ToLowerInvariant());
        Log("hitbox-death-all: " + AkronModule.Settings.HitboxShowAllOnDeath.ToString().ToLowerInvariant());
        Log("hitbox-death-player-marker: " + AkronModule.Settings.HitboxShowDeathPlayerMarker.ToString().ToLowerInvariant());
        LogHitboxStyleSettings();
        Log(AkronEntityInspector.DescribeHitboxPerformance());
        Log("last-death-visible: " + AkronEntityInspector.HasVisibleLastDeathHitbox().ToString().ToLowerInvariant());
        Log("last-death-object: " + (string.IsNullOrWhiteSpace(session?.LastDeathEntityType) ? "unset" : session.LastDeathEntityType));
        Log("inspector: " + AkronModule.Settings.EntityInspector.ToString().ToLowerInvariant());
        Log("step-hold-repeat: " + AkronModule.Settings.StepHoldRepeat.ToString().ToLowerInvariant());
        Log("step-repeat-delay: " + AkronModule.Settings.StepHoldDelayFrames.ToString(CultureInfo.InvariantCulture));
        Log("step-repeat-interval: " + AkronModule.Settings.StepHoldIntervalFrames.ToString(CultureInfo.InvariantCulture));
        Log("infinite-stamina: " + AkronModule.Settings.InfiniteStamina.ToString().ToLowerInvariant());
        Log("infinite-dash: " + AkronModule.Settings.InfiniteDash.ToString().ToLowerInvariant());
        Log("jump-hack: " + AkronModule.Settings.JumpHack.ToString().ToLowerInvariant());
        Log("jump-hack-infinite: " + AkronModule.Settings.JumpHackInfinite.ToString().ToLowerInvariant());
        Log("jump-hack-extra-jumps: " + AkronModule.Settings.JumpHackExtraJumps.ToString(CultureInfo.InvariantCulture));
        Log("auto-kill: " + AkronModule.Settings.AutoKill.ToString().ToLowerInvariant());
        Log("auto-kill-timer: " + AkronModule.Settings.AutoKillTimer.ToString().ToLowerInvariant());
        Log("auto-kill-seconds: " + AkronModule.Settings.AutoKillSeconds.ToString(CultureInfo.InvariantCulture));
        Rectangle autoKillArea = AkronModule.GetAutoKillArea();
        Log("auto-kill-area: " + AkronModule.Settings.AutoKillArea.ToString().ToLowerInvariant());
        Log("auto-kill-area-count: " + AkronModule.GetAutoKillAreas().Count.ToString(CultureInfo.InvariantCulture));
        Log("auto-kill-area-rect: " + autoKillArea.X.ToString(CultureInfo.InvariantCulture) + ", " + autoKillArea.Y.ToString(CultureInfo.InvariantCulture) + ", " + autoKillArea.Width.ToString(CultureInfo.InvariantCulture) + ", " + autoKillArea.Height.ToString(CultureInfo.InvariantCulture));
        Log("auto-kill-show-area: " + AkronModule.Settings.AutoKillShowArea.ToString().ToLowerInvariant());
        Log("auto-kill-show-area-on-death: " + AkronModule.Settings.AutoKillShowAreaOnDeath.ToString().ToLowerInvariant());
        Rectangle autoDeafenArea = AkronModule.GetAutoDeafenArea();
        Log("auto-deafen: " + AkronModule.Settings.AutoDeafen.ToString().ToLowerInvariant());
        Log("auto-deafen-active: " + AkronActions.AutoDeafenActive.ToString().ToLowerInvariant());
        Log("auto-deafen-method: discord-hotkey");
        Log("auto-deafen-hotkey: " + AkronActions.DescribeAutoDeafenHotkey());
        Log("auto-deafen-area: " + AkronModule.Settings.AutoDeafenArea.ToString().ToLowerInvariant());
        Log("auto-deafen-area-count: " + AkronModule.GetAutoDeafenAreas().Count.ToString(CultureInfo.InvariantCulture));
        Log("auto-deafen-area-rect: " + autoDeafenArea.X.ToString(CultureInfo.InvariantCulture) + ", " + autoDeafenArea.Y.ToString(CultureInfo.InvariantCulture) + ", " + autoDeafenArea.Width.ToString(CultureInfo.InvariantCulture) + ", " + autoDeafenArea.Height.ToString(CultureInfo.InvariantCulture));
        Log("auto-deafen-show-area: " + AkronModule.Settings.AutoDeafenShowArea.ToString().ToLowerInvariant());
        Log("transition-speed: " + AkronModule.Settings.TransitionSpeedMultiplier.ToString("0.0x", CultureInfo.InvariantCulture));
        Log("trail-visibility: " + AkronModule.Settings.TrailVisibility);
        Log("trail-cutting-rate: " + AkronModule.Settings.TrailCuttingRate.ToString(CultureInfo.InvariantCulture));
        Log("madeline-colors: " + AkronModule.Settings.MadelineColors.ToString().ToLowerInvariant());
        Log("madeline-color-no-dash: " + AkronModule.Settings.MadelineColorNoDash.ToString().ToLowerInvariant());
        Log("madeline-color-one-dash: " + AkronModule.Settings.MadelineColorOneDash.ToString().ToLowerInvariant());
        Log("madeline-color-two-dash: " + AkronModule.Settings.MadelineColorTwoDash.ToString().ToLowerInvariant());
        Log("madeline-color-three-dash: " + AkronModule.Settings.MadelineColorThreeDash.ToString().ToLowerInvariant());
        Log("madeline-color-four-dash: " + AkronModule.Settings.MadelineColorFourDash.ToString().ToLowerInvariant());
        Log("madeline-color-five-dash: " + AkronModule.Settings.MadelineColorFiveDash.ToString().ToLowerInvariant());
        Log("madeline-gradient: " + AkronModule.Settings.MadelineColorGradient.ToString().ToLowerInvariant());
        Log("madeline-gradient-speed: " + AkronModule.Settings.MadelineColorGradientSpeed.ToString("0.0", CultureInfo.InvariantCulture));
        Log("madeline-no-dash-color: " + FormatRgb(AkronModule.Settings.MadelineNoDashColor));
        Log("madeline-one-dash-color: " + FormatRgb(AkronModule.Settings.MadelineOneDashColor));
        Log("madeline-two-dash-color: " + FormatRgb(AkronModule.Settings.MadelineTwoDashColor));
        Log("madeline-three-dash-color: " + FormatRgb(AkronModule.Settings.MadelineThreeDashColor));
        Log("madeline-four-dash-color: " + FormatRgb(AkronModule.Settings.MadelineFourDashColor));
        Log("madeline-five-dash-color: " + FormatRgb(AkronModule.Settings.MadelineFiveDashColor));
        Log("madeline-gradient-a: " + FormatRgb(AkronModule.Settings.MadelineGradientColorA));
        Log("madeline-gradient-b: " + FormatRgb(AkronModule.Settings.MadelineGradientColorB));
        Log("madeline-hair-length: " + AkronModule.Settings.MadelineHairLength.ToString().ToLowerInvariant());
        Log("madeline-no-dash-hair-length: " + AkronModule.Settings.MadelineNoDashHairLength.ToString(CultureInfo.InvariantCulture));
        Log("madeline-one-dash-hair-length: " + AkronModule.Settings.MadelineOneDashHairLength.ToString(CultureInfo.InvariantCulture));
        Log("madeline-two-dash-hair-length: " + AkronModule.Settings.MadelineTwoDashHairLength.ToString(CultureInfo.InvariantCulture));
        Log("madeline-three-dash-hair-length: " + AkronModule.Settings.MadelineThreeDashHairLength.ToString(CultureInfo.InvariantCulture));
        Log("madeline-four-dash-hair-length: " + AkronModule.Settings.MadelineFourDashHairLength.ToString(CultureInfo.InvariantCulture));
        Log("madeline-five-dash-hair-length: " + AkronModule.Settings.MadelineFiveDashHairLength.ToString(CultureInfo.InvariantCulture));
        Log("madeline-effect-sync: " + AkronModule.Settings.MadelineEffectSync.ToString().ToLowerInvariant());
        Log("madeline-dash-particle-sync: " + AkronModule.Settings.MadelineDashParticleSync);
        Log("madeline-dash-trail-sync: " + AkronModule.Settings.MadelineDashTrailSync);
        Log("madeline-death-effect-sync: " + AkronModule.Settings.MadelineDeathEffectSync);
        Log("madeline-feather-color-sync: " + AkronModule.Settings.MadelineFeatherColorSync);
        Log("madeline-crown-color-sync: " + AkronModule.Settings.MadelineCrownColorSync);
        Log("noclip: " + AkronModule.Settings.Noclip.ToString().ToLowerInvariant());
        Log("noclip-speed: " + AkronModule.Settings.NoclipSpeed.ToString(CultureInfo.InvariantCulture));
        Log("noclip-float-speed: " + AkronModule.Settings.NoclipFloatSpeed.ToString(CultureInfo.InvariantCulture));
        Log("noclip-draw-on-top: " + AkronModule.Settings.NoclipDrawOnTop.ToString().ToLowerInvariant());
        Log("noclip-hide-player: " + AkronModule.Settings.NoclipHidePlayer.ToString().ToLowerInvariant());
        Log("hazard-accuracy: " + AkronModule.Settings.NoclipAccuracy.ToString().ToLowerInvariant());
        Log("hazard-accuracy-tint: " + AkronModule.Settings.NoclipAccuracyTint.ToString().ToLowerInvariant());
        Log("hazard-accuracy-tint-mode: " + AkronModule.Settings.NoclipAccuracyTintMode);
        Log("hazard-accuracy-tint-color: " + FormatRgb(AkronModule.Settings.NoclipAccuracyTintColor));
        Log("hazard-accuracy-tint-opacity: " + AkronModule.Settings.NoclipAccuracyTintOpacity.ToString(CultureInfo.InvariantCulture));
        Log("hazard-accuracy-tint-duration-ms: " + AkronModule.Settings.NoclipAccuracyTintDurationMs.ToString(CultureInfo.InvariantCulture));
        Log("hazard-accuracy-state: " + AkronModule.GetNoclipAccuracySnapshot().Describe());
        Log("invincibility: " + AkronModule.Settings.Invincibility.ToString().ToLowerInvariant());
        Log("respawn-time: " + AkronModule.Settings.RespawnTimeModifier.ToString().ToLowerInvariant());
        Log("respawn-time-seconds: " + AkronModule.Settings.RespawnTimeSeconds.ToString("0.0", CultureInfo.InvariantCulture));
        Log("respawn-time-ignore-speedhack: " + AkronModule.Settings.RespawnTimeIgnoreSpeedhack.ToString().ToLowerInvariant());
        Log("hide-pause-menu: " + AkronModule.Settings.HidePauseMenu.ToString().ToLowerInvariant());
        Log("pause-countdown: " + AkronModule.Settings.PauseCountdown.ToString().ToLowerInvariant());
        Log("pause-countdown-seconds: " + AkronModule.Settings.PauseCountdownSeconds.ToString("0.0", CultureInfo.InvariantCulture));
        Log("pause-countdown-hide-tint: " + AkronModule.Settings.PauseCountdownHidePauseTint.ToString().ToLowerInvariant());
        Log("pause-countdown-remaining: " + AkronModule.PauseCountdownRemaining.ToString("0.0", CultureInfo.InvariantCulture));
        Log("show-trajectory: " + AkronModule.Settings.ShowTrajectory.ToString().ToLowerInvariant());
        Log("show-trajectory-frames: " + AkronModule.Settings.ShowTrajectoryFrames.ToString(CultureInfo.InvariantCulture));
        Log("show-trajectory-press-color: " + FormatRgb(AkronModule.Settings.ShowTrajectoryPressColor));
        Log("show-trajectory-release-color: " + FormatRgb(AkronModule.Settings.ShowTrajectoryReleaseColor));
        Log("show-trajectory-end-color: " + FormatRgb(AkronModule.Settings.ShowTrajectoryEndMarkerColor));
        Log("show-trajectory-use-hitbox-color: " + AkronModule.Settings.ShowTrajectoryUseHitboxColor.ToString().ToLowerInvariant());
        Log("show-trajectory-lines: " + AkronModule.Settings.ShowTrajectoryLines.ToString().ToLowerInvariant());
        Log("show-trajectory-line-shadow: " + AkronModule.Settings.ShowTrajectoryLineShadow.ToString().ToLowerInvariant());
        Log("show-trajectory-point-markers: " + AkronModule.Settings.ShowTrajectoryPointMarkers.ToString().ToLowerInvariant());
        Log("show-trajectory-start-marker: " + AkronModule.Settings.ShowTrajectoryStartMarker.ToString().ToLowerInvariant());
        Log("show-trajectory-end-markers: " + AkronModule.Settings.ShowTrajectoryEndMarkers.ToString().ToLowerInvariant());
        Log("show-trajectory-frame-hitboxes: " + AkronModule.Settings.ShowTrajectoryFrameHitboxes.ToString().ToLowerInvariant());
        Log("show-trajectory-frame-hitbox-interval: " + AkronModule.Settings.ShowTrajectoryFrameHitboxInterval.ToString(CultureInfo.InvariantCulture));
        Log("show-trajectory-hitbox-outlines: " + AkronModule.Settings.ShowTrajectoryHitboxOutlines.ToString().ToLowerInvariant());
        Log("show-trajectory-hitbox-fill: " + AkronModule.Settings.ShowTrajectoryHitboxFill.ToString().ToLowerInvariant());
        Log("show-trajectory-opacity: " + AkronModule.Settings.ShowTrajectoryOpacity.ToString(CultureInfo.InvariantCulture));
        Log("show-trajectory-thickness: " + AkronModule.Settings.ShowTrajectoryLineThickness.ToString(CultureInfo.InvariantCulture));
        Log("show-trajectory-map-aware: " + AkronModule.Settings.ShowTrajectoryMapAware.ToString().ToLowerInvariant());
        Log("show-trajectory-stop-on-solids: " + AkronModule.Settings.ShowTrajectoryStopOnSolids.ToString().ToLowerInvariant());
        Log("show-trajectory-stop-on-hazards: " + AkronModule.Settings.ShowTrajectoryStopOnHazards.ToString().ToLowerInvariant());
        Log("grab-mode: " + Settings.Instance.GrabMode);
        Log("interop-speedruntool: " + AkronInterop.SpeedrunToolLoaded.ToString().ToLowerInvariant());
        Log("interop-roomtimer: " + AkronInterop.RoomTimerAvailable.ToString().ToLowerInvariant());
        Log("interop-celestetas: " + AkronInterop.CelesteTasLoaded.ToString().ToLowerInvariant());
        Log("interop-evm: " + AkronExtendedVariants.Available.ToString().ToLowerInvariant());
        Log("evm-master: " + (AkronExtendedVariants.Available && AkronExtendedVariants.MasterSwitch).ToString().ToLowerInvariant());
        Log("evm-summary: " + AkronExtendedVariants.StatusSummary);
        Log("evm-randomizer: " + (AkronExtendedVariants.Available && AkronExtendedVariants.RandomizerEnabled).ToString().ToLowerInvariant());
        Log("evm-display-enabled: " + (AkronExtendedVariants.Available && AkronExtendedVariants.DisplayEnabledVariants).ToString().ToLowerInvariant());
        Log("evm-variant-count: " + AkronExtendedVariants.GetOptions().Count.ToString(CultureInfo.InvariantCulture));
        Log("tas-active: " + AkronInterop.IsTasActive().ToString().ToLowerInvariant());
        Log("tas-running: " + AkronInterop.IsTasRunning().ToString().ToLowerInvariant());
        Log("tas-file: " + (string.IsNullOrWhiteSpace(AkronModule.Settings.TasFilePath) ? "unset" : AkronModule.Settings.FormatPathForDisplay(AkronModule.Settings.TasFilePath)));
        if (level != null) {
            Log("room: " + level.Session.Area.GetSID() + " / " + level.Session.Level);
            Log("level-in-cutscene: " + level.InCutscene.ToString().ToLowerInvariant());
            Log("level-skipping-cutscene: " + level.SkippingCutscene.ToString().ToLowerInvariant());
            Log("selected-room: " + AkronActions.DescribeSelectedRoom(level));
            Log("selected-flag: " + DescribeSelectedFlag(level));
            Log("editable-flag: " + AkronModule.Settings.EditableFlagName);
            Log("editable-flag-enabled: " + level.Session.GetFlag(AkronModule.Settings.EditableFlagName).ToString().ToLowerInvariant());
            Log("force-broker-override: " + AkronMapOverrides.ShouldForceBroker(level).ToString().ToLowerInvariant());
            Log("unsafe-native-override: " + AkronMapOverrides.ShouldAllowUnsafeSavestates(level).ToString().ToLowerInvariant());
            Log("everest-safe-override: " + AkronMapOverrides.ShouldDisableEverestSafeBlock(level).ToString().ToLowerInvariant());
        }

        if (player != null) {
            Log("player: " + player.Position.X.ToString("0.##", CultureInfo.InvariantCulture) + ", " + player.Position.Y.ToString("0.##", CultureInfo.InvariantCulture));
            Log("stamina: " + player.Stamina.ToString("0.##", CultureInfo.InvariantCulture));
            Log("dashes: " + player.Dashes.ToString(CultureInfo.InvariantCulture));
        }
    }
}
